/** Decorative PNG assets under /public/decorations */
export const DECORATIONS = {
  pearlDrapes: "/narek-serine/images/pearl-drapes1.png",
  bridalHeadpiece: "/narek-serine/decorations/bridal-headpiece.png",
  floralLaceCorner: "/narek-serine/decorations/floral-lace-corner.png",
  flowers: "/narek-serine/decorations/flowers.png",
  ivoryPetals: "/narek-serine/decorations/ivory-petals.png",
  laceFloralSide: "/narek-serine/decorations/lace-floral-side.png",
  pearlButterfly: "/narek-serine/decorations/pearl-butterfly.png",
  silkRibbon: "/narek-serine/images/silk-ribbon.png",
  floatingPetals: "/narek-serine/images/floating-petals.png",
  goldDividerOrnament: "/narek-serine/images/gold-divider-ornament.png",
  goldDividerThin: "/narek-serine/images/ivory-rose-cluster.png",
  goldSparkleWave: "/narek-serine/images/gold-sparkle-wave.png",
  pearlFloralGarland: "/narek-serine/images/pearl-floral-garland.png",
  ivoryRoseCluster: "/narek-serine/images/ivory-rose-cluster.png",
  pearlDropsSet: "/narek-serine/images/pearl-drops-set.png",
  pearlDropsSmall: "/narek-serine/images/pearl-drops-small.png",
  goldPearlRibbon: "/narek-serine/images/gold-pearl-ribbon.png",
} as const;
